#####################################
# CLOUD PROVIDER
#####################################

CLOUD_PROVIDER=aws

#####################################
# COMMON SETTINGS
#####################################

INSTANCE_COUNT=1

INSTANCE_TYPE=t3.micro

INGRESS_PORTS=22,80,443

TAG_NAME=cloud-demo

SSH_USER=ubuntu

PUBLIC_KEY_PATH=$HOME/.ssh/id_rsa.pub

#####################################
# AWS
#####################################

AWS_REGION=ap-south-1
AWS_AMI_ID=ami-0f58b397bc5c1f2e8
AWS_KEY_PAIR=ec2-latest-key.pem
AWS_SECURITY_GROUP=my-terraform-sg

#####################################
# GCP
#####################################

GCP_PROJECT=my-project-id

GCP_REGION=asia-south1

GCP_ZONE=asia-south1-a

GCP_MACHINE_IMAGE=ubuntu-os-cloud/ubuntu-2204-lts

GCP_NETWORK=default

GCP_SUBNETWORK=default
